"""Factory for STT/TTS services based on voice language."""

from __future__ import annotations

import os
from typing import Any, Tuple

import aiohttp
from loguru import logger

from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.services.deepgram.tts import DeepgramHttpTTSService

from app.languages import VoiceLanguageConfig, get_language_config, VoiceLanguageCode

from pipecat.services.tts_service import TTSService
from pipecat.frames.frames import TextFrame, Frame, TTSSpeakFrame, SystemFrame, ControlFrame, StartFrame, CancelFrame, EndFrame
from pipecat.processors.frame_processor import FrameProcessor, FrameDirection
from pipecat.transcriptions.language import Language

class MultilingualTTS(FrameProcessor):
    def __init__(self, services: dict[VoiceLanguageCode, TTSService], initial_lang: VoiceLanguageCode):
        super().__init__()
        self._services = services
        self._current_lang = initial_lang
        self._started = False

    def set_language(self, lang_code: VoiceLanguageCode):
        if lang_code in self._services:
            if self._current_lang != lang_code:
                logger.info(f"MultilingualTTS: switching from {self._current_lang} to {lang_code}")
                self._current_lang = lang_code
        else:
            logger.warning(f"MultilingualTTS: language {lang_code} not supported, keeping {self._current_lang}")

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        if isinstance(frame, (SystemFrame, ControlFrame)):
            await super().process_frame(frame, direction)

        if isinstance(frame, StartFrame):
            self._started = True
            for service in self._services.values():
                await service.queue_frame(frame, direction)
            await self.push_frame(frame, direction)
            return

        if not self._started:
            return

        # Forward system/control frames to all sub-services so they stay in sync
        # (e.g. CancelFrame to stop them, etc.)
        if isinstance(frame, (SystemFrame, ControlFrame)):
            for service in self._services.values():
                await service.queue_frame(frame, direction)

        if isinstance(frame, (TextFrame, TTSSpeakFrame)) and direction == FrameDirection.DOWNSTREAM:
            service = self._services.get(self._current_lang)
            if service:
                # Forward to the active TTS service's queue_frame
                await service.queue_frame(frame, direction)
            else:
                logger.error(f"MultilingualTTS: no service for language {self._current_lang}")
        else:
            await self.push_frame(frame, direction)

    async def _handle_tts_frame(self, frame: Frame, direction: FrameDirection = FrameDirection.DOWNSTREAM):
        if isinstance(frame, (StartFrame, CancelFrame, EndFrame)):
            return
        await self.push_frame(frame, direction)

    async def setup(self, setup):
        await super().setup(setup)
        for code, service in self._services.items():
            await service.setup(setup)
            # Hijack the service's push_frame to point back to our handler.
            # This ensures that audio generated by the sub-services is pushed downstream from US,
            # while filtering out system frames (StartFrame/CancelFrame/EndFrame) which we already propagated.
            service.push_frame = self._handle_tts_frame

    async def cleanup(self):
        await super().cleanup()
        for service in self._services.values():
            await service.cleanup()



from pipecat.services.stt_service import STTService
from pipecat.frames.frames import AudioRawFrame, TranscriptionFrame

class MultilingualSTTRouter(FrameProcessor):
    def __init__(
        self,
        deepgram_stt: STTService,
        sarvam_stt_hi: STTService,
        sarvam_stt_ml: STTService,
        initial_lang: VoiceLanguageCode,
    ):
        super().__init__()
        self._deepgram = deepgram_stt
        self._sarvam_hi = sarvam_stt_hi
        self._sarvam_ml = sarvam_stt_ml
        self._current_lang = initial_lang
        self._started = False

    def set_language(self, lang_code: VoiceLanguageCode):
        if self._current_lang != lang_code:
            logger.info(f"MultilingualSTTRouter: switching from {self._current_lang} to {lang_code}")
            self._current_lang = lang_code

    async def _handle_deepgram_frame(self, frame: Frame, direction: FrameDirection = FrameDirection.DOWNSTREAM):
        if isinstance(frame, (StartFrame, CancelFrame, EndFrame)):
            return
        if isinstance(frame, TranscriptionFrame):
            if self._current_lang == "en":
                await self.push_frame(frame, direction)
            else:
                detected_lang = frame.language
                if detected_lang:
                    from app.languages import normalize_language_code
                    resolved = normalize_language_code(detected_lang)
                    if resolved == "en":
                        logger.info("Deepgram detected switch back to English. Pushing frame downstream.")
                        await self.push_frame(frame, direction)
                    else:
                        logger.debug(f"Discarding Deepgram transcription in {self._current_lang} mode since Sarvam is active.")
        else:
            await self.push_frame(frame, direction)

    async def _handle_sarvam_hi_frame(self, frame: Frame, direction: FrameDirection = FrameDirection.DOWNSTREAM):
        if isinstance(frame, TranscriptionFrame):
            frame.language = "hi"
            if self._current_lang == "hi":
                await self.push_frame(frame, direction)

    async def _handle_sarvam_ml_frame(self, frame: Frame, direction: FrameDirection = FrameDirection.DOWNSTREAM):
        if isinstance(frame, TranscriptionFrame):
            frame.language = "ml"
            if self._current_lang == "ml":
                await self.push_frame(frame, direction)

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        if isinstance(frame, (SystemFrame, ControlFrame)):
            await super().process_frame(frame, direction)

        if isinstance(frame, StartFrame):
            self._started = True
            await self._deepgram.queue_frame(frame, direction)
            await self._sarvam_hi.queue_frame(frame, direction)
            await self._sarvam_ml.queue_frame(frame, direction)
            await self.push_frame(frame, direction)
            return

        if not self._started:
            return

        if isinstance(frame, (SystemFrame, ControlFrame)):
            await self._deepgram.queue_frame(frame, direction)
            await self._sarvam_hi.queue_frame(frame, direction)
            await self._sarvam_ml.queue_frame(frame, direction)
            await self.push_frame(frame, direction)
            return

        if direction == FrameDirection.DOWNSTREAM:
            await self._deepgram.queue_frame(frame, direction)
            if self._current_lang == "hi":
                await self._sarvam_hi.queue_frame(frame, direction)
            elif self._current_lang == "ml":
                await self._sarvam_ml.queue_frame(frame, direction)
        else:
            await self.push_frame(frame, direction)

    async def setup(self, setup):
        await super().setup(setup)
        await self._deepgram.setup(setup)
        await self._sarvam_hi.setup(setup)
        await self._sarvam_ml.setup(setup)
        self._deepgram.push_frame = self._handle_deepgram_frame
        self._sarvam_hi.push_frame = self._handle_sarvam_hi_frame
        self._sarvam_ml.push_frame = self._handle_sarvam_ml_frame

    async def cleanup(self):
        await super().cleanup()
        await self._deepgram.cleanup()
        await self._sarvam_hi.cleanup()
        await self._sarvam_ml.cleanup()


def resolve_voice_language(language: str | None = None) -> VoiceLanguageConfig:
    """Return config for the given code or the default from environment."""
    return get_language_config(language or os.environ.get("VOICE_LANGUAGE"))


def create_stt_tts(
    lang: VoiceLanguageConfig,
    session: aiohttp.ClientSession,
    multilingual: bool = False,
) -> Tuple[Any, Any]:
    """Return (stt, tts) for the given language configuration."""
    sarvam_api_key = os.environ.get("SARVAM_API_KEY", "").strip()
    deepgram_key = os.environ.get("DEEPGRAM_API_KEY", "").strip()

    if multilingual:
        if sarvam_api_key:
            from pipecat.services.sarvam.stt import SarvamSTTService
            logger.info("Using Sarvam AI STT in multilingual mode (auto-detecting English, Hindi, Malayalam)")
            stt = SarvamSTTService(
                api_key=sarvam_api_key,
                mode="transcribe",
                audio_passthrough=False,
                settings=SarvamSTTService.Settings(
                    model="saaras:v3",
                    language=None,  # None triggers auto-detection / "unknown"
                ),
            )
        else:
            if not deepgram_key:
                raise RuntimeError("Either SARVAM_API_KEY or DEEPGRAM_API_KEY is required.")
            logger.info("Using Deepgram Multilingual STT (auto-detecting en, hi, ml)")
            stt = DeepgramSTTService(
                api_key=deepgram_key,
                settings=DeepgramSTTService.Settings(
                    model="nova-2",
                    smart_format=True,
                    language="multi",  # Auto-detection
                    endpointing=100,
                ),
            )

        # Create all 3 TTS services for MultilingualTTS
        from app.languages import SUPPORTED_LANGUAGES
        tts_services = {}
        for code in SUPPORTED_LANGUAGES:
            tts_services[code] = create_tts_service(get_language_config(code), session)

        tts = MultilingualTTS(tts_services, lang.code)
        return stt, tts

    if lang.uses_sarvam and sarvam_api_key:
        from pipecat.services.sarvam.stt import SarvamSTTService
        logger.info(f"Using Sarvam AI STT for {lang.label} ({lang.code})")
        stt = SarvamSTTService(
            api_key=sarvam_api_key,
            mode="transcribe",
            settings=SarvamSTTService.Settings(
                model="saaras:v3",
                language=lang.pipecat_language,
            ),
        )
    else:
        if not deepgram_key:
            raise RuntimeError("DEEPGRAM_API_KEY is required for Deepgram fallback.")
        logger.info(f"Using Deepgram STT fallback for {lang.label}")
        stt = DeepgramSTTService(
            api_key=deepgram_key,
            settings=DeepgramSTTService.Settings(
                model="nova-2",
                smart_format=True,
                language=lang.code,
            ),
        )

    tts = create_tts_service(lang, session)
    return stt, tts


def create_tts_service(lang: VoiceLanguageConfig, session: aiohttp.ClientSession) -> Any:
    """Create a TTS service for a specific language."""

    cartesia_api_key = os.environ.get("CARTESIA_API_KEY", "").strip()
    if cartesia_api_key and lang.code == "ml":
        from pipecat.services.cartesia.tts import CartesiaHttpTTSService
        voice_id = os.environ.get("CARTESIA_ML_VOICE_ID") or "b426013c-002b-4e89-8874-8cd20b68373a" # Latha - Friendly Host
        model = os.environ.get("CARTESIA_MODEL_ID") or "sonic-3.5"
        logger.info(f"Creating Cartesia TTS service for Malayalam using model={model}, voice={voice_id}")
        return CartesiaHttpTTSService(
            api_key=cartesia_api_key,
            voice_id=voice_id,
            model=model,
            aiohttp_session=session,
        )

    sarvam_api_key = os.environ.get("SARVAM_API_KEY", "").strip()
    if sarvam_api_key:
        from pipecat.services.sarvam.tts import SarvamHttpTTSService
        if lang.code == "ml":
            speaker = os.environ.get("SARVAM_ML_SPEAKER") or "shreya"
        elif lang.code == "hi":
            speaker = os.environ.get("SARVAM_HI_SPEAKER") or "shreya"
        else:
            speaker = os.environ.get("SARVAM_EN_SPEAKER") or "shreya"
        model = os.environ.get("SARVAM_TTS_MODEL") or "bulbul:v3"
        logger.info(f"Creating Sarvam TTS service for language={lang.code} using model={model}, speaker={speaker}")
        return SarvamHttpTTSService(
            api_key=sarvam_api_key,
            aiohttp_session=session,
            settings=SarvamHttpTTSService.Settings(
                model=model,
                language=lang.pipecat_language,
                voice=speaker,
            ),
        )

    
    deepgram_key = os.environ.get("DEEPGRAM_API_KEY", "").strip()
    if not deepgram_key:
        raise RuntimeError("DEEPGRAM_API_KEY is required for Deepgram TTS fallback.")
    return DeepgramHttpTTSService(
        api_key=deepgram_key,
        settings=DeepgramHttpTTSService.Settings(
            voice="aura-2-andromeda-en",
        ),
        aiohttp_session=session,
    )


def _default_sarvam_speaker(code: str) -> str:
    return {
        "en": os.environ.get("SARVAM_EN_SPEAKER", "priya"),
        "hi": os.environ.get("SARVAM_HI_SPEAKER", "priya"),
        "ml": os.environ.get("SARVAM_ML_SPEAKER", "kavitha"),
    }.get(code, "priya")
