"""Factory for STT/TTS services based on voice language."""

from __future__ import annotations

import os
from typing import Any, Tuple

import aiohttp
from loguru import logger

from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.services.deepgram.tts import DeepgramHttpTTSService

from app.languages import VoiceLanguageConfig, get_language_config, VoiceLanguageCode

from pipecat.services.tts_service import TTSService
from pipecat.frames.frames import TextFrame, Frame, TTSSpeakFrame, SystemFrame, ControlFrame
from pipecat.processors.frame_processor import FrameProcessor, FrameDirection

class MultilingualTTS(FrameProcessor):
    def __init__(self, services: dict[VoiceLanguageCode, TTSService], initial_lang: VoiceLanguageCode):
        super().__init__()
        self._services = services
        self._current_lang = initial_lang

    def set_language(self, lang_code: VoiceLanguageCode):
        if lang_code in self._services:
            if self._current_lang != lang_code:
                logger.info(f"MultilingualTTS: switching from {self._current_lang} to {lang_code}")
                self._current_lang = lang_code
        else:
            logger.warning(f"MultilingualTTS: language {lang_code} not supported, keeping {self._current_lang}")

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        # Forward system/control frames to all sub-services so they stay in sync
        # (e.g. StartFrame to start their tasks, CancelFrame to stop them, etc.)
        if isinstance(frame, (SystemFrame, ControlFrame)):
            for service in self._services.values():
                await service.queue_frame(frame, direction)

        if isinstance(frame, (TextFrame, TTSSpeakFrame)) and direction == FrameDirection.DOWNSTREAM:
            service = self._services.get(self._current_lang)
            if service:
                # Forward to the active TTS service's queue_frame
                await service.queue_frame(frame, direction)
            else:
                logger.error(f"MultilingualTTS: no service for language {self._current_lang}")
        else:
            # For all other frames (including system frames), push downstream normally
            await self.push_frame(frame, direction)

    async def setup(self, setup):
        await super().setup(setup)
        for code, service in self._services.items():
            await service.setup(setup)
            # Hijack the service's push_frame to point back to our push_frame
            # This ensures that audio generated by the sub-services is pushed downstream from US.
            service.push_frame = self.push_frame

def resolve_voice_language(language: str | None = None) -> VoiceLanguageConfig:
    """Return config for the given code or the default from environment."""
    return get_language_config(language or os.environ.get("VOICE_LANGUAGE"))


def create_stt_tts(
    lang: VoiceLanguageConfig,
    session: aiohttp.ClientSession,
    multilingual: bool = False,
) -> Tuple[Any, Any]:
    """Return (stt, tts) for the given language configuration."""
    deepgram_key = os.environ.get("DEEPGRAM_API_KEY", "").strip()
    if not deepgram_key:
        raise RuntimeError("DEEPGRAM_API_KEY is required.")

    if multilingual:
        logger.info("Using Deepgram Multilingual STT (auto-detecting en, hi, ml)")
        # Deepgram Nova-2 supports multi-language detection
        stt = DeepgramSTTService(
            api_key=deepgram_key,
            settings=DeepgramSTTService.Settings(
                model="nova-2",
                smart_format=True,
                language=None,  # Auto-detection
            ),
        )

        # Create all 3 TTS services for MultilingualTTS
        from app.languages import SUPPORTED_LANGUAGES
        tts_services = {}
        for code in SUPPORTED_LANGUAGES:
            tts_services[code] = create_tts_service(get_language_config(code), session)

        tts = MultilingualTTS(tts_services, lang.code)
        return stt, tts

    if lang.uses_sarvam:

        api_key = os.environ.get("SARVAM_API_KEY", "").strip()
        if not api_key:
            raise RuntimeError(
                f"SARVAM_API_KEY is required for {lang.label} (VOICE_LANGUAGE={lang.code}). "
                "Set it in your .env file."
            )

        from pipecat.services.sarvam.stt import SarvamSTTService
        logger.info(f"Using Sarvam AI STT for {lang.label} ({lang.code})")
        stt = SarvamSTTService(
            api_key=api_key,
            mode="transcribe",
            settings=SarvamSTTService.Settings(
                model="saaras:v3",
                language=lang.pipecat_language,
            ),
        )
    else:
        logger.info("Using Deepgram STT for English")
        stt = DeepgramSTTService(
            api_key=deepgram_key,
            settings=DeepgramSTTService.Settings(
                model="nova-2",
                smart_format=True,
                language="en",
            ),
        )

    # TTS is language-specific in this project (Sarvam for hi/ml, Deepgram for en)
    tts = create_tts_service(lang, session)
    return stt, tts


def create_tts_service(lang: VoiceLanguageConfig, session: aiohttp.ClientSession) -> Any:
    """Create a TTS service for a specific language."""
    if lang.uses_sarvam:
        api_key = os.environ.get("SARVAM_API_KEY", "").strip()
        from pipecat.services.sarvam.tts import SarvamHttpTTSService
        return SarvamHttpTTSService(
            api_key=api_key,
            aiohttp_session=session,
            settings=SarvamHttpTTSService.Settings(
                model="bulbul:v3",
                language=lang.pipecat_language,
                voice=_default_sarvam_speaker(lang.code),
            ),
        )
    
    deepgram_key = os.environ.get("DEEPGRAM_API_KEY", "").strip()
    return DeepgramHttpTTSService(
        api_key=deepgram_key,
        settings=DeepgramHttpTTSService.Settings(
            voice="aura-2-andromeda-en",
        ),
        aiohttp_session=session,
    )


def _default_sarvam_speaker(code: str) -> str:
    return {
        "hi": os.environ.get("SARVAM_HI_SPEAKER", "priya"),
        "ml": os.environ.get("SARVAM_ML_SPEAKER", "anushka"),
    }.get(code, "priya")
